Nex 79 routes and pages created
nickvprince/Nexum pull request #18
Opened 2024-04-12 00:21 UTC by Babywise

- Basic MVC implementation
- Main pages are 'functional' showing dummy data which is retrieved from the api
- Basic Bootstrap css
- Barebones with many not implement exception functions

2024-05-08 18:16 UTC, dsmith2304 commented
Will download and review later today.

2024-05-08 20:44 UTC, dsmith2304 requested changes
Several Connection Refused errors when clicking any buttons on main page, or login

![on-login](https://github.com/nickvprince/Nexum/assets/78614204/977a2606-55bb-4ba9-a200-a09fed70b8eb)
![accounts](https://github.com/nickvprince/Nexum/assets/78614204/166cecc6-c27b-45a3-9861-4482963c0aca)

2024-05-19 22:35 UTC, dsmith2304 approved these changes

2024-05-19 22:35 UTC, nickvprince approved these changes

2024-05-19 22:37 UTC, merged